id: 3c11d171-e2ad-4d26-a034-04f3b062306c
schema: https://metadata.datadrivendiscovery.org/schemas/v0/pipeline.json
source:
  name: Mitar
created: "2018-07-28T01:24:39.642266Z"
context: TESTING
name: Train-test split of tabular datasets
description: |
  Train-test split of tabular datasets.
inputs:
  - name: folds
  - name: full dataset
outputs:
  - name: train datasets
    data: steps.0.produce
  - name: test datasets
    data: steps.2.produce
  - name: score datasets
    data: steps.1.produce
steps:
  # Step 0.
  - type: PRIMITIVE
    primitive:
      id: 3fcc6dc4-6681-4c86-948e-066d14e7d803
      version: 0.1.0
      python_path: d3m.primitives.evaluation.train_score_dataset_split.Common
      name: Train-score tabular dataset splits
    arguments:
      inputs:
        type: CONTAINER
        data: inputs.0
      dataset:
        type: CONTAINER
        data: inputs.1
    outputs:
      - id: produce
      - id: produce_score_data
  # Step 1. We redact privileged attributes for both score and test splits.
  - type: PRIMITIVE
    primitive:
      id: 744c4090-e2f6-489e-8efc-8b1e051bfad6
      version: 0.2.0
      python_path: d3m.primitives.evaluation.redact_columns.Common
      name: Redact columns for evaluation
    arguments:
      inputs:
        type: CONTAINER
        data: steps.0.produce_score_data
    outputs:
      - id: produce
    hyperparams:
      semantic_types:
        type: VALUE
        data:
          - https://metadata.datadrivendiscovery.org/types/PrivilegedData
      add_semantic_types:
        type: VALUE
        data:
          - https://metadata.datadrivendiscovery.org/types/RedactedPrivilegedData
          - https://metadata.datadrivendiscovery.org/types/MissingData
  # Step 2. We further redact targets in test split.
  - type: PRIMITIVE
    primitive:
      id: 744c4090-e2f6-489e-8efc-8b1e051bfad6
      version: 0.2.0
      python_path: d3m.primitives.evaluation.redact_columns.Common
      name: Redact columns for evaluation
    arguments:
      inputs:
        type: CONTAINER
        data: steps.1.produce
    outputs:
      - id: produce
    hyperparams:
      semantic_types:
        type: VALUE
        data:
          - https://metadata.datadrivendiscovery.org/types/TrueTarget
      add_semantic_types:
        type: VALUE
        data:
          - https://metadata.datadrivendiscovery.org/types/RedactedTarget
          - https://metadata.datadrivendiscovery.org/types/MissingData