S -> CLASSIFICATION_TASK | REGRESSION_TASK | TIME_SERIES_CLASSIFICATION_TASK | TIME_SERIES_FORECASTING_TASK | COMMUNITY_DETECTION_TASK | GRAPH_MATCHING_TASK | COLLABORATIVE_FILTERING_TASK | VERTEX_CLASSIFICATION_TASK | LINK_PREDICTION_TASK | OBJECT_DETECTION_TASK | SEMISUPERVISED_CLASSIFICATION_TASK | CLUSTERING_TASK | TEXT_CLASSIFICATION_TASK | IMAGE_CLASSIFICATION_TASK | AUDIO_CLASSIFICATION_TASK | TEXT_REGRESSION_TASK | IMAGE_REGRESSION_TASK | AUDIO_REGRESSION_TASK | LUPI_TASK | VIDEO_CLASSIFICATION_TASK | NA_TASK
CLASSIFICATION_TASK -> IMPUTATION ENCODERS 'd3m.primitives.data_transformation.to_numeric.DSBOX' FEATURE_SCALING FEATURE_SELECTION CLASSIFICATION
REGRESSION_TASK -> IMPUTATION ENCODERS 'd3m.primitives.data_transformation.to_numeric.DSBOX' FEATURE_SCALING FEATURE_SELECTION REGRESSION
TIME_SERIES_CLASSIFICATION_TASK -> TIME_SERIES_READER TIME_SERIES_FEATURIZER FEATURE_SCALING CLASSIFICATION
TIME_SERIES_FORECASTING_TASK ->  IMPUTATION TIME_SERIES_GROUPER TIME_SERIES_FORECASTING | REGRESSION_TASK
COMMUNITY_DETECTION_TASK -> GRAPH_LOADER COMMUNITY_DETECTION | GRAPH_LOADER NONOVERLAPPING_COMMUNITY_DETECTION SINGULAR_VALUE_DECOMPOSITION COMMUNITY_DETECTION | CLASSIFICATION_TASK
GRAPH_MATCHING_TASK -> GRAPH_LOADER GRAPH_MATCHING | GRAPH_MATCHING | CLASSIFICATION_TASK
COLLABORATIVE_FILTERING_TASK -> IMPUTATION ENCODERS FEATURE_SCALING COLLABORATIVE_FILTERING
VERTEX_CLASSIFICATION_TASK -> GRAPH_LOADER VERTEX_CLASSIFICATION | GRAPH_LOADER NONOVERLAPPING_COMMUNITY_DETECTION SINGULAR_VALUE_DECOMPOSITION VERTEX_CLASSIFICATION | CLASSIFICATION_TASK
LINK_PREDICTION_TASK -> GRAPH_LOADER LINK_PREDICTION | CLASSIFICATION_TASK
OBJECT_DETECTION_TASK -> OBJECT_DETECTION
CLUSTERING_TASK -> IMPUTATION ENCODERS FEATURE_SCALING FEATURE_SELECTION CLUSTERING
SEMISUPERVISED_CLASSIFICATION_TASK -> IMPUTATION ENCODERS FEATURE_SELECTION CLASSIFICATION SEMISUPERVISED_CLASSIFICATION
LUPI_TASK -> ENCODERS IMPUTATION FEATURE_SCALING FEATURE_SELECTION CLASSIFICATION
TEXT_CLASSIFICATION_TASK -> TEXT_FEATURIZER FEATURE_SELECTION CLASSIFICATION | TEXT_CLASSIFIER
TEXT_REGRESSION_TASK -> TEXT_FEATURIZER FEATURE_SELECTION REGRESSION
IMAGE_CLASSIFICATION_TASK -> TO_TENSOR IMAGE_FEATURIZER  CLASSIFICATION
IMAGE_REGRESSION_TASK -> TO_TENSOR IMAGE_FEATURIZER REGRESSION
AUDIO_CLASSIFICATION_TASK -> AUDIO_READER AUDIO_FEATURIZER CLASSIFICATION
AUDIO_REGRESSION_TASK -> AUDIO_READER AUDIO_FEATURIZER REGRESSION
VIDEO_CLASSIFICATION_TASK -> VIDEO_FEATURIZER CLASSIFICATION
VIDEO_REGRESSION_TASK -> VIDEO_FEATURIZER REGRESSION
NA_TASK -> CLASSIFICATION_TASK | REGRESSION_TASK
ENCODERS -> TEXT_FEATURIZER DATETIME_ENCODER CATEGORICAL_ENCODER
IMPUTATION -> 'primitive_terminal'
FEATURE_SELECTION -> 'primitive_terminal' | 'E'
FEATURE_SCALING -> 'primitive_terminal' | 'E'
CLASSIFICATION -> 'primitive_terminal'
REGRESSION -> 'primitive_terminal'
TIME_SERIES_CLASSIFICATION -> 'primitive_terminal'
TIME_SERIES_FORECASTING -> 'primitive_terminal'
COMMUNITY_DETECTION -> 'primitive_terminal'
GRAPH_MATCHING -> 'primitive_terminal'
COLLABORATIVE_FILTERING -> 'primitive_terminal'
VERTEX_CLASSIFICATION -> 'primitive_terminal'
LINK_PREDICTION -> 'primitive_terminal'
SEMISUPERVISED_CLASSIFICATION -> 'primitive_terminal'
CLUSTERING -> 'primitive_terminal'
OBJECT_DETECTION -> 'primitive_terminal'
TEXT_CLASSIFIER -> 'primitive_terminal'
CATEGORICAL_ENCODER -> 'primitive_terminal'
DATETIME_ENCODER -> 'primitive_terminal'
TEXT_FEATURIZER -> 'primitive_terminal'
IMAGE_FEATURIZER -> 'primitive_terminal'
AUDIO_FEATURIZER -> 'primitive_terminal'
VIDEO_FEATURIZER -> 'primitive_terminal'
TIME_SERIES_FEATURIZER -> 'primitive_terminal'
AUDIO_READER -> 'primitive_terminal'
TIME_SERIES_READER -> 'primitive_terminal'
TIME_SERIES_GROUPER -> 'primitive_terminal'
GRAPH_LOADER -> 'primitive_terminal'
NONOVERLAPPING_COMMUNITY_DETECTION -> 'primitive_terminal'
SINGULAR_VALUE_DECOMPOSITION -> 'primitive_terminal'
TO_TENSOR -> 'primitive_terminal' | 'E'