S -> CLASSIFICATION_TASK | REGRESSION_TASK
CLASSIFICATION_TASK -> IMPUTATION ENCODERS FEATURE_SCALING FEATURE_SELECTION CLASSIFICATION
REGRESSION_TASK -> IMPUTATION ENCODERS FEATURE_SCALING FEATURE_SELECTION REGRESSION
CLUSTERING_TASK -> IMPUTATION ENCODERS FEATURE_SCALING FEATURE_SELECTION CLUSTERING
NA_TASK -> CLASSIFICATION_TASK | REGRESSION_TASK
ENCODERS -> TEXT_ENCODER DATETIME_ENCODER CATEGORICAL_ENCODER
IMPUTATION -> 'primitive_terminal'
FEATURE_SCALING -> 'primitive_terminal' | 'E'
FEATURE_SELECTION -> 'primitive_terminal' | 'E'
TEXT_ENCODER -> 'primitive_terminal'
CATEGORICAL_ENCODER -> 'primitive_terminal'
DATETIME_ENCODER -> 'primitive_terminal'
CLASSIFICATION -> 'primitive_terminal'
REGRESSION -> 'primitive_terminal'
CLUSTERING -> 'primitive_terminal'
