S -> CLASSIFICATION_TASK | REGRESSION_TASK
CLASSIFICATION_TASK -> CLASSIFICATION | DATA_CLEANING CLASSIFICATION | DATA_TRANSFORMATION CLASSIFICATION | DATA_CLEANING DATA_TRANSFORMATION CLASSIFICATION
REGRESSION_TASK -> REGRESSION | DATA_CLEANING REGRESSION | DATA_TRANSFORMATION REGRESSION | DATA_CLEANING DATA_TRANSFORMATION REGRESSION
CLASSIFICATION -> 'primitive_terminal'
REGRESSION -> 'primitive_terminal'
DATA_CLEANING -> 'primitive_terminal' DATA_CLEANING | 'E'
DATA_TRANSFORMATION -> 'primitive_terminal' DATA_TRANSFORMATION | 'E'